### ISSUE TITLE
Question about reward function

### ISSUE THREAD

**Issue by Nicholas-tlc** [NithishkumarS/DWA-RL#3]
Hi, Is the reward function the latest version in the code? Because I found that the setting of reward in the code is different from that in the paper. The paper also contains a Steer reward. I really hope you can reply to me as soon as possible. 
I would appreciate it if you could reply to me
,Thank you so much!!

**Comment by NithishkumarS** [comment]
We haven't made that part of the code public. But you could add the steer reward yourself to ` compute_reward()` in the source file located at ```
DWA-RL/openai_ros/openai_ros/src/openai_ros/task_envs/turtlebot2/turtlebot2_maze.py ```.
All the input sources needed are available in the same class.
